import { OrbitState } from './models';

export function createSeedState(): OrbitState {
  return {
    version: 1,
    sessionUserId: null,
    users: [
      {
        id: 'user-admin',
        name: 'Andrea Vega',
        email: 'admin@orbit.demo',
        role: 'admin',
        initials: 'AV',
        title: 'Administradora de plataforma',
        color: '#625bf6',
      },
      {
        id: 'user-hr',
        name: 'Mariana Torres',
        email: 'rh@orbit.demo',
        role: 'hr',
        initials: 'MT',
        title: 'People Operations',
        color: '#e86f51',
      },
      {
        id: 'user-manager',
        name: 'Diego Hernández',
        email: 'manager@orbit.demo',
        role: 'manager',
        initials: 'DH',
        title: 'Engineering Manager',
        color: '#1d9c73',
      },
      {
        id: 'user-it',
        name: 'Sofía Ramírez',
        email: 'ti@orbit.demo',
        role: 'it',
        initials: 'SR',
        title: 'IT Operations',
        color: '#3276e8',
      },
    ],
    sites: [
      {
        id: 'site-gdl',
        name: 'Guadalajara HQ',
        city: 'Guadalajara, Jalisco',
        address: 'Av. Vallarta 6503, Ciudad Granja',
      },
      {
        id: 'site-cdmx',
        name: 'Ciudad de México',
        city: 'Ciudad de México',
        address: 'Paseo de la Reforma 250, Cuauhtémoc',
      },
      {
        id: 'site-mty',
        name: 'Monterrey',
        city: 'Monterrey, Nuevo León',
        address: 'Av. Lázaro Cárdenas 2400, Valle Oriente',
      },
    ],
    departments: [
      {
        id: 'dep-eng',
        name: 'Engineering',
        code: 'ENG',
        manager: 'Diego Hernández',
        siteId: 'site-gdl',
        color: '#625bf6',
      },
      {
        id: 'dep-people',
        name: 'People & Culture',
        code: 'P&C',
        manager: 'Mariana Torres',
        siteId: 'site-gdl',
        color: '#e86f51',
      },
      {
        id: 'dep-ops',
        name: 'Operations',
        code: 'OPS',
        manager: 'Daniela Soto',
        siteId: 'site-cdmx',
        color: '#1d9c73',
      },
      {
        id: 'dep-fin',
        name: 'Finance',
        code: 'FIN',
        manager: 'Carlos Luna',
        siteId: 'site-mty',
        color: '#e5a436',
      },
      {
        id: 'dep-it',
        name: 'IT Operations',
        code: 'ITO',
        manager: 'Sofía Ramírez',
        siteId: 'site-gdl',
        color: '#3276e8',
      },
    ],
    employees: [
      {
        id: 'emp-001',
        name: 'Diego Hernández',
        email: 'diego.hernandez@orbit.demo',
        jobTitle: 'Engineering Manager',
        departmentId: 'dep-eng',
        siteId: 'site-gdl',
        managerId: 'emp-001',
        status: 'active',
        startDate: '2024-02-12',
        onboardingProgress: 100,
        assetIds: ['asset-001'],
        avatarColor: '#1d9c73',
      },
      {
        id: 'emp-002',
        name: 'Mariana Torres',
        email: 'mariana.torres@orbit.demo',
        jobTitle: 'People Operations Lead',
        departmentId: 'dep-people',
        siteId: 'site-gdl',
        managerId: 'emp-002',
        status: 'active',
        startDate: '2023-09-18',
        onboardingProgress: 100,
        assetIds: ['asset-002'],
        avatarColor: '#e86f51',
      },
      {
        id: 'emp-003',
        name: 'Sofía Ramírez',
        email: 'sofia.ramirez@orbit.demo',
        jobTitle: 'IT Operations Specialist',
        departmentId: 'dep-it',
        siteId: 'site-gdl',
        managerId: 'emp-001',
        status: 'active',
        startDate: '2024-06-03',
        onboardingProgress: 100,
        assetIds: ['asset-003'],
        avatarColor: '#3276e8',
      },
      {
        id: 'emp-004',
        name: 'Valeria Cruz',
        email: 'valeria.cruz@orbit.demo',
        jobTitle: 'Frontend Developer',
        departmentId: 'dep-eng',
        siteId: 'site-gdl',
        managerId: 'emp-001',
        status: 'active',
        startDate: '2025-01-20',
        onboardingProgress: 100,
        assetIds: ['asset-004'],
        avatarColor: '#9b69d1',
      },
      {
        id: 'emp-005',
        name: 'Emilio Navarro',
        email: 'emilio.navarro@orbit.demo',
        jobTitle: 'Backend Developer',
        departmentId: 'dep-eng',
        siteId: 'site-gdl',
        managerId: 'emp-001',
        status: 'onboarding',
        startDate: '2026-08-17',
        onboardingProgress: 60,
        assetIds: [],
        avatarColor: '#d15b87',
      },
      {
        id: 'emp-006',
        name: 'Fernanda Ruiz',
        email: 'fernanda.ruiz@orbit.demo',
        jobTitle: 'Operations Analyst',
        departmentId: 'dep-ops',
        siteId: 'site-cdmx',
        managerId: 'emp-001',
        status: 'active',
        startDate: '2025-11-10',
        onboardingProgress: 100,
        assetIds: ['asset-006'],
        avatarColor: '#e5a436',
      },
      {
        id: 'emp-007',
        name: 'Carlos Luna',
        email: 'carlos.luna@orbit.demo',
        jobTitle: 'Finance Manager',
        departmentId: 'dep-fin',
        siteId: 'site-mty',
        managerId: 'emp-007',
        status: 'active',
        startDate: '2024-08-05',
        onboardingProgress: 100,
        assetIds: ['asset-007'],
        avatarColor: '#4f91c9',
      },
      {
        id: 'emp-008',
        name: 'Lucía Méndez',
        email: 'lucia.mendez@orbit.demo',
        jobTitle: 'QA Engineer',
        departmentId: 'dep-eng',
        siteId: 'site-gdl',
        managerId: 'emp-001',
        status: 'inactive',
        startDate: '2025-03-03',
        onboardingProgress: 100,
        assetIds: [],
        avatarColor: '#7986a8',
      },
    ],
    assets: [
      {
        id: 'asset-001',
        name: 'MacBook Pro 14',
        type: 'Laptop',
        brand: 'Apple',
        model: 'M3 Pro',
        serial: 'ORB-MBP-24001',
        status: 'assigned',
        assignedTo: 'emp-001',
        siteId: 'site-gdl',
        purchaseDate: '2024-02-01',
      },
      {
        id: 'asset-002',
        name: 'ThinkPad X1 Carbon',
        type: 'Laptop',
        brand: 'Lenovo',
        model: 'Gen 12',
        serial: 'ORB-LNV-24012',
        status: 'assigned',
        assignedTo: 'emp-002',
        siteId: 'site-gdl',
        purchaseDate: '2024-01-15',
      },
      {
        id: 'asset-003',
        name: 'Dell Latitude 7450',
        type: 'Laptop',
        brand: 'Dell',
        model: 'Latitude 7450',
        serial: 'ORB-DLL-24018',
        status: 'assigned',
        assignedTo: 'emp-003',
        siteId: 'site-gdl',
        purchaseDate: '2024-05-24',
      },
      {
        id: 'asset-004',
        name: 'MacBook Air 15',
        type: 'Laptop',
        brand: 'Apple',
        model: 'M3',
        serial: 'ORB-MBA-25004',
        status: 'assigned',
        assignedTo: 'emp-004',
        siteId: 'site-gdl',
        purchaseDate: '2025-01-10',
      },
      {
        id: 'asset-005',
        name: 'MacBook Pro 14',
        type: 'Laptop',
        brand: 'Apple',
        model: 'M4 Pro',
        serial: 'ORB-MBP-26021',
        status: 'available',
        assignedTo: null,
        siteId: 'site-gdl',
        purchaseDate: '2026-07-28',
      },
      {
        id: 'asset-006',
        name: 'Dell Latitude 5440',
        type: 'Laptop',
        brand: 'Dell',
        model: 'Latitude 5440',
        serial: 'ORB-DLL-25026',
        status: 'assigned',
        assignedTo: 'emp-006',
        siteId: 'site-cdmx',
        purchaseDate: '2025-10-27',
      },
      {
        id: 'asset-007',
        name: 'HP EliteBook 840',
        type: 'Laptop',
        brand: 'HP',
        model: 'G11',
        serial: 'ORB-HP-24031',
        status: 'assigned',
        assignedTo: 'emp-007',
        siteId: 'site-mty',
        purchaseDate: '2024-07-19',
      },
      {
        id: 'asset-008',
        name: 'Dell UltraSharp 27',
        type: 'Monitor',
        brand: 'Dell',
        model: 'U2723QE',
        serial: 'ORB-MON-26008',
        status: 'available',
        assignedTo: null,
        siteId: 'site-gdl',
        purchaseDate: '2026-06-11',
      },
      {
        id: 'asset-009',
        name: 'ThinkPad T14',
        type: 'Laptop',
        brand: 'Lenovo',
        model: 'Gen 5',
        serial: 'ORB-LNV-25037',
        status: 'maintenance',
        assignedTo: null,
        siteId: 'site-cdmx',
        purchaseDate: '2025-05-08',
      },
    ],
    requests: [
      {
        id: 'req-001',
        code: 'REQ-1024',
        title: 'Laptop para nuevo ingreso',
        category: 'Equipo',
        description: 'Preparar laptop de desarrollo para Emilio antes de su primer día.',
        requesterId: 'user-hr',
        employeeId: 'emp-005',
        approverId: 'emp-001',
        priority: 'high',
        status: 'pending_approval',
        assetId: null,
        createdAt: '2026-08-13T16:20:00.000Z',
        updatedAt: '2026-08-13T16:20:00.000Z',
      },
      {
        id: 'req-002',
        code: 'REQ-1023',
        title: 'Acceso al repositorio de plataforma',
        category: 'Acceso',
        description: 'Acceso de lectura y escritura para el equipo de Engineering.',
        requesterId: 'user-manager',
        employeeId: 'emp-004',
        approverId: 'emp-001',
        priority: 'medium',
        status: 'approved',
        assetId: null,
        createdAt: '2026-08-12T14:10:00.000Z',
        updatedAt: '2026-08-13T09:30:00.000Z',
      },
      {
        id: 'req-003',
        code: 'REQ-1022',
        title: 'Licencia de diseño colaborativo',
        category: 'Software',
        description: 'Licencia profesional para el equipo de producto.',
        requesterId: 'user-hr',
        employeeId: 'emp-002',
        approverId: 'emp-001',
        priority: 'low',
        status: 'completed',
        assetId: null,
        createdAt: '2026-08-08T18:05:00.000Z',
        updatedAt: '2026-08-11T17:45:00.000Z',
      },
      {
        id: 'req-004',
        code: 'REQ-1021',
        title: 'Monitor adicional para home office',
        category: 'Equipo',
        description: 'Monitor de 27 pulgadas para mejorar el espacio de trabajo.',
        requesterId: 'user-manager',
        employeeId: 'emp-004',
        approverId: 'emp-001',
        priority: 'medium',
        status: 'in_progress',
        assetId: null,
        createdAt: '2026-08-07T15:15:00.000Z',
        updatedAt: '2026-08-12T13:20:00.000Z',
      },
      {
        id: 'req-005',
        code: 'REQ-1020',
        title: 'Acceso temporal a finanzas',
        category: 'Acceso',
        description: 'Acceso por auditoría interna durante dos semanas.',
        requesterId: 'user-admin',
        employeeId: 'emp-006',
        approverId: 'emp-007',
        priority: 'high',
        status: 'rejected',
        assetId: null,
        createdAt: '2026-08-06T12:30:00.000Z',
        updatedAt: '2026-08-06T16:25:00.000Z',
      },
    ],
    audit: [
      {
        id: 'audit-001',
        action: 'Solicitud creada',
        resource: 'Solicitud',
        resourceId: 'REQ-1024',
        actor: 'Mariana Torres',
        actorRole: 'hr',
        details: 'Solicitud de laptop creada para Emilio Navarro.',
        timestamp: '2026-08-13T16:20:00.000Z',
      },
      {
        id: 'audit-002',
        action: 'Empleado registrado',
        resource: 'Empleado',
        resourceId: 'EMP-005',
        actor: 'Mariana Torres',
        actorRole: 'hr',
        details: 'Emilio Navarro fue agregado al directorio e inició onboarding.',
        timestamp: '2026-08-13T16:18:00.000Z',
      },
      {
        id: 'audit-003',
        action: 'Solicitud aprobada',
        resource: 'Solicitud',
        resourceId: 'REQ-1023',
        actor: 'Diego Hernández',
        actorRole: 'manager',
        details: 'Acceso al repositorio aprobado para Valeria Cruz.',
        timestamp: '2026-08-13T09:30:00.000Z',
      },
      {
        id: 'audit-004',
        action: 'Estado actualizado',
        resource: 'Solicitud',
        resourceId: 'REQ-1021',
        actor: 'Sofía Ramírez',
        actorRole: 'it',
        details: 'La solicitud de monitor cambió a En proceso.',
        timestamp: '2026-08-12T13:20:00.000Z',
      },
      {
        id: 'audit-005',
        action: 'Solicitud completada',
        resource: 'Solicitud',
        resourceId: 'REQ-1022',
        actor: 'Sofía Ramírez',
        actorRole: 'it',
        details: 'Licencia de diseño asignada correctamente.',
        timestamp: '2026-08-11T17:45:00.000Z',
      },
      {
        id: 'audit-006',
        action: 'Activo asignado',
        resource: 'Activo',
        resourceId: 'ORB-DLL-25026',
        actor: 'Sofía Ramírez',
        actorRole: 'it',
        details: 'Dell Latitude 5440 asignada a Fernanda Ruiz.',
        timestamp: '2026-08-10T15:35:00.000Z',
      },
    ],
  };
}
